import {
  runPdfExport,
  type PdfAssetResolver,
  type PdfCompilePort,
  type PdfCompilerDiagnostic,
  type PdfExportReport,
  type ResolvedPdfFontRequirementsV1,
  type PdfSourceBundle,
} from "@atlcli/pdf/browser";
import { ATLCLI_TYPST_TEMPLATE, validatePdfOutput } from "@atlcli/pdf/internal";
import { PDF_BLOCKS, PDF_FILENAME, PDF_METADATA } from "./fixture.js";
import { MemoryOutputSink } from "./memory-output.js";
import { HarnessPdfWorkerClient } from "./pdf-worker-client.js";

const compiler = new HarnessPdfWorkerClient();

const noAssets: PdfAssetResolver = {
  async resolve(): Promise<never> {
    throw new Error("The deterministic harness fixture has no external assets.");
  },
};

function deterministicClock(): () => number {
  let tick = 0;
  return () => tick++;
}

function equalBytes(left: Uint8Array, right: Uint8Array): boolean {
  if (left.byteLength !== right.byteLength) return false;
  return left.every((byte, index) => byte === right[index]);
}

function assertNormalizedDiagnostic(diagnostic: PdfCompilerDiagnostic): void {
  const raw = diagnostic as PdfCompilerDiagnostic & { package?: unknown; range?: unknown };
  if ("package" in raw || "range" in raw) {
    throw new Error("A raw compiler diagnostic escaped the browser compiler package.");
  }
  if (!diagnostic.blockPath) {
    throw new Error("The invalid-source diagnostic was not mapped to its source block.");
  }
}

async function diagnosticProbe(
  fontRequirements: ResolvedPdfFontRequirementsV1,
): Promise<PdfCompilerDiagnostic[]> {
  const invalid: PdfSourceBundle = {
    main: "#function-that-does-not-exist()",
    template: ATLCLI_TYPST_TEMPLATE,
    assets: [],
    notes: [],
    fontRequirements,
    sourceMap: [
      {
        blockPath: "blocks[0]",
        blockType: "paragraph",
        startLine: 1,
        startColumn: 1,
        endLine: 2,
        endColumn: 1,
      },
    ],
  };
  const result = await compiler.compile(invalid);
  if (result.pdf || result.diagnostics.length === 0) {
    throw new Error("The invalid-source compiler probe did not return diagnostics.");
  }
  for (const diagnostic of result.diagnostics) assertNormalizedDiagnostic(diagnostic);
  return result.diagnostics;
}

async function onePdfRun(): Promise<{
  report: PdfExportReport;
  bytes: Uint8Array;
}> {
  const output = new MemoryOutputSink();
  const report = await runPdfExport(
    {
      blocks: PDF_BLOCKS,
      sourceNotes: [
        {
          level: "info",
          code: "browser-harness",
          message: "Generated by the neutral browser conformance harness.",
        },
      ],
      metadata: PDF_METADATA,
      profile: "tagged",
      filename: PDF_FILENAME,
    },
    {
      assets: noAssets,
      compiler,
      output,
      now: deterministicClock(),
    },
  );
  return { report, bytes: output.single.bytes };
}

export interface PdfCaseResult {
  filename: string;
  byteLength: number;
  byteIdenticalWarmRepeat: boolean;
  pageCount: number;
  tagged: boolean;
  hasOutline: boolean;
  embeddedFontFiles: number;
  compilerVersion: string;
  diagnosticCount: number;
  workerGeneration: number;
  fontRequirementCount: number;
  registeredFontAssetIds: readonly string[];
  fullBundleFallback: boolean;
}

export async function runPdfCase(): Promise<PdfCaseResult> {
  const first = await onePdfRun();
  const second = await onePdfRun();
  const firstInspection = validatePdfOutput(first.bytes);
  const secondInspection = validatePdfOutput(second.bytes);
  if (!equalBytes(first.bytes, second.bytes)) {
    throw new Error("Warm PDF compilation was not byte-identical.");
  }
  if (!firstInspection.tagged || !firstInspection.hasOutline || firstInspection.embeddedFontFiles < 1) {
    throw new Error("PDF output is missing tags, outline, or embedded fonts.");
  }
  if (JSON.stringify(firstInspection) !== JSON.stringify(secondInspection)) {
    throw new Error("Warm PDF structural inspection changed between runs.");
  }
  if (!first.report.compilerVersion || first.report.compilerVersion === "unknown") {
    throw new Error("The PDF report did not expose the compiler version.");
  }
  if (first.report.notes[0]?.code !== "browser-harness") {
    throw new Error("The runner did not preserve source-note ordering.");
  }
  if (!first.report.fontRequirements || !first.report.fontEvidence) {
    throw new Error("The browser PDF report omitted font requirements or load evidence.");
  }
  const expectedAssetIds = first.report.fontRequirements.assets.map(
    (asset) => asset.assetId,
  );
  if (
    first.report.fontEvidence.fullBundleFallback ||
    JSON.stringify(first.report.fontEvidence.registeredAssetIds) !==
      JSON.stringify(expectedAssetIds)
  ) {
    throw new Error("The browser PDF compiler did not register the resolved font subset.");
  }
  const diagnostics = await diagnosticProbe(first.report.fontRequirements);

  return {
    filename: first.report.filename,
    byteLength: first.bytes.byteLength,
    byteIdenticalWarmRepeat: true,
    pageCount: firstInspection.pageCount,
    tagged: firstInspection.tagged,
    hasOutline: firstInspection.hasOutline,
    embeddedFontFiles: firstInspection.embeddedFontFiles,
    compilerVersion: first.report.compilerVersion,
    diagnosticCount: diagnostics.length,
    workerGeneration: compiler.workerGeneration,
    fontRequirementCount: expectedAssetIds.length,
    registeredFontAssetIds: first.report.fontEvidence.registeredAssetIds,
    fullBundleFallback: first.report.fontEvidence.fullBundleFallback,
  };
}

export interface PdfAbortCaseResult {
  aborted: boolean;
  emittedOutputs: number;
  workerWasReplaced: boolean;
}

export async function runPdfAbortCase(): Promise<PdfAbortCaseResult> {
  const controller = new AbortController();
  const output = new MemoryOutputSink();
  const generationBefore = compiler.workerGeneration;
  const abortingCompiler: PdfCompilePort = {
    compile(bundle, context) {
      const pending = compiler.compile(bundle, context);
      queueMicrotask(() => controller.abort());
      return pending;
    },
  };

  let rejected = false;
  try {
    await runPdfExport(
      {
        blocks: PDF_BLOCKS,
        metadata: PDF_METADATA,
        filename: PDF_FILENAME,
        signal: controller.signal,
      },
      {
        assets: noAssets,
        compiler: abortingCompiler,
        output,
        now: deterministicClock(),
      },
    );
  } catch {
    rejected = true;
  }
  if (!controller.signal.aborted || !rejected || output.emissions.length !== 0) {
    throw new Error("An aborted PDF request reached output emission.");
  }
  const workerWasReplaced = compiler.workerGeneration > generationBefore;
  if (!workerWasReplaced) throw new Error("Active abort did not terminate the harness Worker.");

  return {
    aborted: true,
    emittedOutputs: output.emissions.length,
    workerWasReplaced,
  };
}
