import type {
  ExportJobExecutionContext,
  PdfExportJobRequestV1,
  PendingArtifactV1,
  StagedArtifactV1,
} from "@atlcli/export-jobs";
import {
  createPdfExportJobExecutor,
  type CreatePdfExportJobExecutorOptionsV1,
  type PdfExportJobEngineInputV1,
  type PdfExportResultIntentV1,
  type PdfReadyToRenderCheckpointV1,
  type PdfReadyToRenderStoreV1,
} from "@atlcli/export-wiring/jobs";
import {
  runPdfExport,
  type PdfCompilePort,
  type PdfExportReport,
} from "@atlcli/pdf/browser";
import { PDF_BLOCKS, PDF_FILENAME, PDF_METADATA } from "./fixture.js";
import { sha256Hex } from "./digest.js";
import { assertPdfJobParity } from "./pdf-job-parity.js";
import { MemoryOutputSink } from "./memory-output.js";
import { deterministicClock, noPdfAssets } from "./pdf-run.js";
import { HarnessPdfWorkerClient } from "./pdf-worker-client.js";

const SOURCE_NOTE = {
  level: "info" as const,
  code: "browser-harness" as const,
  message: "Generated by the PDF job parity case.",
};

const ENGINE_INPUT = {
  blocks: PDF_BLOCKS,
  metadata: PDF_METADATA,
  profile: "tagged" as const,
  filename: PDF_FILENAME,
  sourceNotes: [SOURCE_NOTE],
};

const REQUEST: PdfExportJobRequestV1 = {
  schema: "atlcli.export-job-request/1",
  id: "browser-pdf-parity-job",
  idempotencyKey: "browser-pdf-parity-request-v1",
  format: "pdf",
  renderer: "pdf-typst",
  source: {
    kind: "confluence",
    siteOrigin: "https://example.atlassian.net",
    locator: { kind: "page-id", id: "42", version: 1 },
    scope: { kind: "page" },
  },
  authRef: "browser-harness",
  displayName: "PDF job parity",
  requestedFilename: PDF_FILENAME,
  createdAt: 1,
  priority: "interactive",
  output: { policy: "collect" },
  template: { id: "default", manifestVersion: "1" },
  settings: {},
  options: { resolveMacros: false, profile: "tagged" },
};

export interface PdfJobParityFixtureV1 {
  request: PdfExportJobRequestV1;
  input: PdfExportJobEngineInputV1;
  resolveInput?: CreatePdfExportJobExecutorOptionsV1["resolveInput"];
}

const DEFAULT_FIXTURE: PdfJobParityFixtureV1 = {
  request: REQUEST,
  input: ENGINE_INPUT,
};

async function collect(source: AsyncIterable<Uint8Array>): Promise<Uint8Array> {
  const chunks: Uint8Array[] = [];
  let length = 0;
  for await (const chunk of source) {
    const owned = chunk.slice();
    chunks.push(owned);
    length += owned.byteLength;
  }
  const bytes = new Uint8Array(length);
  let offset = 0;
  for (const chunk of chunks) {
    bytes.set(chunk, offset);
    offset += chunk.byteLength;
  }
  return bytes;
}

interface PdfJobParityCompiler extends PdfCompilePort {
  readonly workerGeneration: number;
  dispose(): void;
}

export interface PdfJobParityCaseOptions {
  createCompiler?: () => PdfJobParityCompiler;
  fixture?: PdfJobParityFixtureV1;
}

async function directRun(
  compiler: PdfCompilePort,
  fixture: PdfJobParityFixtureV1,
) {
  const output = new MemoryOutputSink();
  const report = await runPdfExport(fixture.input, {
    assets: noPdfAssets,
    compiler,
    output,
    now: deterministicClock(),
  });
  return { report, bytes: output.single.bytes };
}

async function jobRun(
  compiler: PdfCompilePort,
  fixture: PdfJobParityFixtureV1,
): Promise<{
  bytes: Uint8Array;
  report: PdfExportReport;
  checkpointRef: string;
  renderAttempts: number;
  reservationReleased: boolean;
}> {
  let checkpoint: PdfReadyToRenderCheckpointV1 | undefined;
  let prepared: Parameters<PdfReadyToRenderStoreV1["commit"]>[0]["prepared"] | undefined;
  let stagedBytes: Uint8Array | undefined;
  let stagedReport: PdfExportReport | undefined;
  let stagedArtifact: StagedArtifactV1 | undefined;
  let resultIntent: PdfExportResultIntentV1 | undefined;
  let checkpointRef = "";
  let reservationReleased = false;
  let time = 0;
  const now = () => time++;

  const executor = createPdfExportJobExecutor({
    resolveInput: fixture.resolveInput ?? (async () => ({
      input: fixture.input,
      env: { assets: noPdfAssets },
    })),
    readyToRender: {
      async load() {
        return checkpoint;
      },
      async commit(input) {
        prepared = structuredClone(input.prepared);
        checkpoint = {
          schema: "atlcli.pdf-ready-to-render/1",
          ref: `ready:${input.jobId}:${input.leaseEpoch}`,
          jobId: input.jobId,
          requestId: input.request.id,
          requestKey: input.request.idempotencyKey,
          preparedRef: `prepared:${input.jobId}:${input.leaseEpoch}`,
          preparedByteLength: input.binding.byteLength,
          preparedSha256: input.binding.sha256,
          estimate: input.estimate,
          renderAttempts: 0,
        };
        return checkpoint;
      },
      async materialize() {
        if (!prepared) throw new Error("PDF parity prepared bundle is missing.");
        return structuredClone(prepared);
      },
      async beginRenderAttempt(input) {
        checkpoint = { ...input.checkpoint, renderAttempts: input.checkpoint.renderAttempts + 1 };
        return checkpoint;
      },
    },
    estimateRender() {
      return {
        heapBytes: 4 * 1024 * 1024,
        spoolBytes: 0,
        outputBytes: 4 * 1024 * 1024,
        rasterPixels: 0,
        confidence: "estimated",
      };
    },
    compiler,
    renderReservations: {
      async acquire() {
        return {
          async reconcile() {},
          release: () => { reservationReleased = true; },
        };
      },
    },
    results: {
      async recover() {
        return undefined;
      },
      async prepare(input) {
        resultIntent = structuredClone(input.intent);
        stagedReport = structuredClone(input.report);
        return structuredClone(input.intent);
      },
      async stage(input, context) {
        if (!resultIntent || resultIntent.key.ref !== input.intent.key.ref) {
          throw new Error("PDF parity result intent is missing or mismatched.");
        }
        stagedArtifact = await context.artifacts.stage(input.artifact, {
          signal: context.signal,
        });
        return {
          stagedArtifact,
          reportRef: resultIntent.reportRef,
          reportSummary: structuredClone(resultIntent.reportSummary),
        };
      },
    },
    now,
  });

  const context: ExportJobExecutionContext = {
    jobId: fixture.request.id,
    leaseEpoch: 1,
    signal: new AbortController().signal,
    spool: {
      async put(): Promise<never> {
        throw new Error("PDF parity executor unexpectedly wrote source spool bytes.");
      },
      async *read(): AsyncIterable<Uint8Array> {
        throw new Error("PDF parity executor unexpectedly read source spool bytes.");
      },
      async stat() {
        return undefined;
      },
    },
    artifacts: {
      async stage(artifact: PendingArtifactV1): Promise<StagedArtifactV1> {
        stagedBytes = await collect(artifact.bytes);
        if (stagedBytes.byteLength !== artifact.byteLength) {
          throw new Error("PDF job staged artifact length does not match its metadata.");
        }
        if (await sha256Hex(stagedBytes) !== artifact.sha256) {
          throw new Error("PDF job staged artifact digest does not match its metadata.");
        }
        stagedArtifact = {
          ref: "artifact:browser-pdf-parity-job:1",
          mediaType: artifact.mediaType,
          filename: artifact.filename,
          byteLength: artifact.byteLength,
          sha256: artifact.sha256,
          jobId: fixture.request.id,
          leaseEpoch: 1,
          stagedAt: now(),
        };
        return stagedArtifact;
      },
      async getStaged() {
        return stagedArtifact;
      },
    },
    async updateProgress() {},
    async appendEvent() {},
    async checkpoint(ref) {
      checkpointRef = ref;
    },
  };

  const result = await executor.execute(fixture.request, context);
  if (!stagedBytes || !stagedReport || !checkpoint) {
    throw new Error("PDF job executor did not stage its artifact, report, and checkpoint.");
  }
  if (result.stagedArtifact.ref !== stagedArtifact?.ref) {
    throw new Error("PDF job result did not reference the staged artifact.");
  }
  if (!resultIntent || result.reportRef !== resultIntent.reportRef) {
    throw new Error("PDF job result did not reference the staged report.");
  }
  return {
    bytes: stagedBytes,
    report: stagedReport,
    checkpointRef,
    renderAttempts: checkpoint.renderAttempts,
    reservationReleased,
  };
}

export async function runPdfJobParityCase(options: PdfJobParityCaseOptions = {}) {
  const createCompiler = options.createCompiler ?? (() => new HarnessPdfWorkerClient());
  const fixture = options.fixture ?? DEFAULT_FIXTURE;
  const directCompiler = createCompiler();
  const direct = await (async () => {
    try {
      return await directRun(directCompiler, fixture);
    } finally {
      directCompiler.dispose();
    }
  })();

  const jobCompiler = createCompiler();
  try {
    let jobCompileCalls = 0;
    const measuredJobCompiler: PdfCompilePort = {
      compile(bundle, context) {
        jobCompileCalls += 1;
        return jobCompiler.compile(bundle, context);
      },
    };
    const job = await jobRun(measuredJobCompiler, fixture);
    const parity = assertPdfJobParity(direct, job);
    if (!job.checkpointRef.startsWith("ready:")) {
      throw new Error("PDF job did not publish its ready-to-render checkpoint.");
    }
    if (job.renderAttempts !== 1) {
      throw new Error(`PDF job used ${job.renderAttempts} render attempts instead of one.`);
    }
    if (!job.reservationReleased) {
      throw new Error("PDF job did not release its heavy render reservation.");
    }
    if (jobCompileCalls !== 1 || jobCompiler.workerGeneration < 1) {
      throw new Error(
        `PDF job used ${jobCompileCalls} compiler calls and ${jobCompiler.workerGeneration} Worker generations.`,
      );
    }
    return {
      ...parity,
      usedRealExecutor: true,
      usedRealWorker: true,
      jobCompileCalls,
      renderAttempts: job.renderAttempts,
      reservationReleased: job.reservationReleased,
    };
  } finally {
    jobCompiler.dispose();
  }
}
