// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
  site: 'https://atlcli.sh',
  integrations: [
    starlight({
      title: 'atlcli',
      description: 'Extensible CLI for Atlassian products',
      components: {
        Footer: './src/components/Footer.astro',
      },
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/BjoernSchotte/atlcli',
        },
      ],
      editLink: {
        baseUrl: 'https://github.com/BjoernSchotte/atlcli/edit/main/',
      },
      customCss: ['./src/styles/custom.css'],
      sidebar: [
        { label: 'Getting Started', link: '/getting-started/' },
        {
          label: 'Confluence',
          collapsed: false,
          items: [
            { label: 'Overview', link: '/confluence/' },
            { label: 'Sync', link: '/confluence/sync/' },
            { label: 'Pages', link: '/confluence/pages/' },
            { label: 'Spaces', link: '/confluence/spaces/' },
            { label: 'Folders', link: '/confluence/folders/' },
            { label: 'Search', link: '/confluence/search/' },
            { label: 'Comments', link: '/confluence/comments/' },
            { label: 'Labels', link: '/confluence/labels/' },
            { label: 'History', link: '/confluence/history/' },
            { label: 'Templates', link: '/confluence/templates/' },
            { label: 'Macros', link: '/confluence/macros/' },
            { label: 'Scroll Compatibility Macros', link: '/confluence/scroll-macros/' },
            { label: 'Dynamic Macros', link: '/confluence/dynamic-macros/' },
            { label: 'Attachments', link: '/confluence/attachments/' },
            { label: 'Webhooks', link: '/confluence/webhooks/' },
            { label: 'Validation', link: '/confluence/validation/' },
            { label: 'Audit', link: '/confluence/audit/' },
            { label: 'Export', link: '/confluence/export/' },
            { label: 'DOCX Import', link: '/confluence/import-docx/' },
            { label: 'PDF Import', link: '/confluence/import-pdf/' },
            { label: 'Export Template Library', link: '/confluence/export-templates/' },
            { label: 'Create a PDF Template from YAML', link: '/confluence/pdf-template-from-yaml/' },
            { label: 'Create a PDF Template from Word', link: '/confluence/pdf-template-from-word/' },
            { label: 'Macro Compatibility', link: '/confluence/macro-compatibility/' },
            { label: 'Ignore Patterns', link: '/confluence/ignore/' },
            { label: 'File Format', link: '/confluence/file-format/' },
            { label: 'Storage Format', link: '/confluence/storage/' },
          ],
        },
        {
          label: 'Web Publishing',
          collapsed: false,
          items: [
            { label: 'Publish with Astro', link: '/publishing/' },
            { label: 'Configuration', link: '/publishing/configuration/' },
            { label: 'Experience Adapter Authoring', link: '/publishing/adapter-authoring/' },
            { label: 'Search and Indexing', link: '/publishing/search/' },
            { label: 'Renderers and Charts', link: '/publishing/renderers/' },
            { label: 'Confluence Charts', link: '/publishing/charts/' },
            { label: 'Security and Privacy', link: '/publishing/security/' },
            { label: 'Operations and Rollback', link: '/publishing/operations/' },
            { label: 'Troubleshooting', link: '/publishing/troubleshooting/' },
          ],
        },
        {
          label: 'Jira',
          collapsed: false,
          items: [
            { label: 'Overview', link: '/jira/' },
            { label: 'Issues', link: '/jira/issues/' },
            { label: 'Search', link: '/jira/search/' },
            { label: 'Projects', link: '/jira/projects/' },
            { label: 'Boards & Sprints', link: '/jira/boards-sprints/' },
            { label: 'Time Tracking', link: '/jira/time-tracking/' },
            { label: 'Epics', link: '/jira/epics/' },
            { label: 'Subtasks', link: '/jira/subtasks/' },
            { label: 'Attachments', link: '/jira/attachments/' },
            { label: 'Analytics', link: '/jira/analytics/' },
            { label: 'Bulk Operations', link: '/jira/bulk-operations/' },
            { label: 'Filters', link: '/jira/filters/' },
            { label: 'Templates', link: '/jira/templates/' },
            { label: 'Import/Export', link: '/jira/import-export/' },
            { label: 'Webhooks', link: '/jira/webhooks/' },
            { label: 'Fields', link: '/jira/fields/' },
          ],
        },
        {
          label: 'Browser Extension',
          collapsed: false,
          items: [
            { label: 'Overview', link: '/extension/' },
            { label: 'Exporting from the panel', link: '/extension/export/' },
          ],
        },
        {
          label: 'Recipes',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/recipes/' },
            { label: 'Team Docs Sync', link: '/recipes/team-docs/' },
            { label: 'Sprint Reporting', link: '/recipes/sprint-reporting/' },
            { label: 'CI/CD Docs', link: '/recipes/ci-cd-docs/' },
            { label: 'Export Automation', link: '/recipes/export-automation/' },
            { label: 'Issue Triage', link: '/recipes/issue-triage/' },
          ],
        },
        {
          label: 'Plugins',
          collapsed: true,
          items: [
            { label: 'Overview', link: '/plugins/' },
            { label: 'Using Plugins', link: '/plugins/using-plugins/' },
            { label: 'Creating Plugins', link: '/plugins/creating-plugins/' },
            { label: 'Git Plugin', link: '/plugins/plugin-git/' },
          ],
        },
        {
          label: 'Reference',
          collapsed: true,
          items: [
            { label: 'CLI Commands', link: '/reference/cli-commands/' },
            { label: 'Atlassian Action Palette', link: '/reference/action-palette/' },
            { label: 'Jira and Confluence Research', link: '/reference/research/' },
            { label: 'DOCX Export Engine', link: '/reference/docx-engine/' },
            { label: 'PDF Export Engine', link: '/reference/pdf-engine/' },
            { label: 'Export Jobs & Operations', link: '/reference/export-jobs/' },
            { label: 'Public Export API (v1)', link: '/reference/export-api/' },
            { label: 'ExportBlock Astro Render Kit', link: '/reference/export-blocks-astro/' },
            { label: 'Consuming the Packages', link: '/reference/package-consumption/' },
            { label: 'Export Asset Contract', link: '/reference/asset-contract/' },
            { label: 'Package Versioning', link: '/reference/versioning/' },
            { label: 'PDF Template Settings', link: '/reference/pdf-template-settings/' },
            { label: 'PDF Template Authoring CLI', link: '/reference/pdf-template-authoring-cli/' },
            { label: 'PDF Template Contract', link: '/reference/pdf-template-contract/' },
            { label: 'PDF Accessibility & PDF/UA', link: '/reference/pdf-accessibility/' },
            { label: 'Template Pack Format', link: '/reference/template-pack-format/' },
            { label: 'Export Performance Envelope', link: '/reference/export-performance/' },
            { label: 'Authentication', link: '/authentication/' },
            { label: 'Configuration', link: '/configuration/' },
            { label: 'Doctor', link: '/reference/doctor/' },
            { label: 'Shell Completion', link: '/reference/shell-completions/' },
            { label: 'Updating', link: '/reference/updating/' },
            { label: 'Development Releases', link: '/reference/dev-releases/' },
            { label: 'Logging', link: '/reference/logging/' },
            { label: 'Environment', link: '/reference/environment/' },
            { label: 'Troubleshooting', link: '/reference/troubleshooting/' },
          ],
        },
        { label: 'Contributing', link: '/contributing/' },
      ],
      // i18n infrastructure (English only for now)
      defaultLocale: 'root',
      locales: {
        root: { label: 'English', lang: 'en' },
        // de: { label: 'Deutsch', lang: 'de' },  // Future
      },
    }),
  ],
});
