import { bundledLanguagesInfo, bundledThemes, bundledThemesInfo } from "shiki";
import { normalizeTheme } from "shiki/core";

const SHIKI_RUNTIME_PACKAGES = [
  "shiki",
  "@shikijs/langs",
  "@shikijs/themes",
] as const;

function opaqueHex(value: string): `#${string}` {
  const hex = value.slice(1);
  const expanded =
    hex.length === 3 || hex.length === 4
      ? [...hex].map((digit) => digit + digit).join("")
      : hex;
  return `#${expanded.slice(0, 6).toUpperCase()}`;
}

const catalogueTarget = new URL("../src/catalogue.generated.ts", import.meta.url);
const loadersTarget = new URL("../src/loaders.generated.ts", import.meta.url);
const themes = await Promise.all(
  bundledThemesInfo.map(async ({ id, displayName, type }) => {
    const module = await bundledThemes[id]();
    const theme = normalizeTheme("default" in module ? module.default : module);
    return {
      id,
      displayName,
      type,
      foreground: opaqueHex(theme.fg),
      background: opaqueHex(theme.bg),
    };
  }),
);

const languages = bundledLanguagesInfo.map(({ id, name, aliases = [] }) => ({
  id,
  name,
  aliases: [...aliases].sort(),
}));

const catalogueSource = `// Generated by scripts/generate-catalogue.ts from Shiki's pinned bundled catalogue.
// Do not edit by hand. Run \`bun run catalogue:generate\`.

export const CODE_THEMES = ${JSON.stringify(themes, null, 2)} as const;

export const CODE_LANGUAGES = ${JSON.stringify(languages, null, 2)} as const;
`;

const languageLoaderEntries = languages
  .map(
    ({ id }) =>
      `  ${JSON.stringify(id)}: () => import(${JSON.stringify(`@shikijs/langs/${id}`)}),`,
  )
  .join("\n");
const themeLoaderEntries = themes
  .map(
    ({ id }) =>
      `  ${JSON.stringify(id)}: () => import(${JSON.stringify(`@shikijs/themes/${id}`)}),`,
  )
  .join("\n");
const loadersSource = `// Generated by scripts/generate-catalogue.ts from Shiki's pinned bundled catalogue.
// Do not edit by hand. Run \`bun run catalogue:generate\`.
//
// Every loader uses a literal package subpath so browser bundlers discover one
// chunk edge per supported runtime module without retaining Shiki's aggregate
// language or theme import maps.

import type { LanguageInput, ThemeInput } from "shiki/core";

type CodeLanguageId =
  (typeof import("./catalogue.generated.js").CODE_LANGUAGES)[number]["id"];
type CodeThemeId =
  (typeof import("./catalogue.generated.js").CODE_THEMES)[number]["id"];

export interface CodeLanguageModule {
  default: LanguageInput;
}

export interface CodeThemeModule {
  default: ThemeInput;
}

export const CODE_LANGUAGE_LOADERS: Record<
  CodeLanguageId,
  () => Promise<CodeLanguageModule>
> = {
${languageLoaderEntries}
};

export const CODE_THEME_LOADERS: Record<
  CodeThemeId,
  () => Promise<CodeThemeModule>
> = {
${themeLoaderEntries}
};
`;

async function assertDirectModulesResolve(): Promise<void> {
  for (const { id } of languages) {
    Bun.resolveSync(`@shikijs/langs/${id}`, import.meta.dir);
  }
  for (const { id } of themes) {
    Bun.resolveSync(`@shikijs/themes/${id}`, import.meta.dir);
  }
}

async function assertRuntimeVersionsPinnedTogether(): Promise<void> {
  const manifest = await Bun.file(
    new URL("../package.json", import.meta.url),
  ).json() as { dependencies?: Record<string, string> };
  const installed = await Promise.all(
    SHIKI_RUNTIME_PACKAGES.map(async (name) => {
      const packageJson = Bun.resolveSync(`${name}/package.json`, import.meta.dir);
      const metadata = await Bun.file(packageJson).json() as { version?: string };
      return [name, metadata.version] as const;
    }),
  );
  const versions = new Set(installed.map(([, version]) => version));
  if (versions.size !== 1 || versions.has(undefined)) {
    throw new Error(
      `Shiki runtime packages must resolve to one version: ${installed
        .map(([name, version]) => `${name}@${version ?? "unknown"}`)
        .join(", ")}`,
    );
  }
  const [version] = versions as Set<string>;
  for (const name of SHIKI_RUNTIME_PACKAGES) {
    if (manifest.dependencies?.[name] !== version) {
      throw new Error(
        `${name} must be pinned to ${version} in packages/code-highlight/package.json`,
      );
    }
  }
}

await assertRuntimeVersionsPinnedTogether();
await assertDirectModulesResolve();

if (process.argv.includes("--check")) {
  const [currentCatalogue, currentLoaders] = await Promise.all([
    Bun.file(catalogueTarget).text(),
    Bun.file(loadersTarget).text(),
  ]);
  if (
    currentCatalogue !== catalogueSource ||
    currentLoaders !== loadersSource
  ) {
    console.error("Shiki catalogue is stale. Run: bun run --cwd packages/code-highlight catalogue:generate");
    process.exit(1);
  }
} else {
  await Promise.all([
    Bun.write(catalogueTarget, catalogueSource),
    Bun.write(loadersTarget, loadersSource),
  ]);
}
