import { bundledLanguagesInfo, bundledThemes, bundledThemesInfo } from "shiki";
import { normalizeTheme } from "shiki/core";

function opaqueHex(value: string): `#${string}` {
  const hex = value.slice(1);
  const expanded =
    hex.length === 3 || hex.length === 4
      ? [...hex].map((digit) => digit + digit).join("")
      : hex;
  return `#${expanded.slice(0, 6).toUpperCase()}`;
}

const target = new URL("../src/catalogue.generated.ts", import.meta.url);
const themes = await Promise.all(
  bundledThemesInfo.map(async ({ id, displayName, type }) => {
    const module = await bundledThemes[id]();
    const theme = normalizeTheme("default" in module ? module.default : module);
    return {
      id,
      displayName,
      type,
      foreground: opaqueHex(theme.fg),
      background: opaqueHex(theme.bg),
    };
  }),
);

const languages = bundledLanguagesInfo.map(({ id, name, aliases = [] }) => ({
  id,
  name,
  aliases: [...aliases].sort(),
}));

const source = `// Generated by scripts/generate-catalogue.ts from Shiki's pinned bundled catalogue.
// Do not edit by hand. Run \`bun run catalogue:generate\`.

export const CODE_THEMES = ${JSON.stringify(themes, null, 2)} as const;

export const CODE_LANGUAGES = ${JSON.stringify(languages, null, 2)} as const;
`;

if (process.argv.includes("--check")) {
  const current = await Bun.file(target).text();
  if (current !== source) {
    console.error("Shiki catalogue is stale. Run: bun run --cwd packages/code-highlight catalogue:generate");
    process.exit(1);
  }
} else {
  await Bun.write(target, source);
}
