// Generated by scripts/generate-catalogue.ts from Shiki's pinned bundled catalogue.
// Do not edit by hand. Run `bun run catalogue:generate`.

export const CODE_THEMES = [
  {
    "id": "andromeeda",
    "displayName": "Andromeeda",
    "type": "dark",
    "foreground": "#D5CED9",
    "background": "#23262E"
  },
  {
    "id": "aurora-x",
    "displayName": "Aurora X",
    "type": "dark",
    "foreground": "#BBBBBB",
    "background": "#07090F"
  },
  {
    "id": "ayu-dark",
    "displayName": "Ayu Dark",
    "type": "dark",
    "foreground": "#BFBDB6",
    "background": "#0D1017"
  },
  {
    "id": "ayu-light",
    "displayName": "Ayu Light",
    "type": "light",
    "foreground": "#5C6166",
    "background": "#F8F9FA"
  },
  {
    "id": "ayu-mirage",
    "displayName": "Ayu Mirage",
    "type": "dark",
    "foreground": "#CCCAC2",
    "background": "#1F2430"
  },
  {
    "id": "catppuccin-frappe",
    "displayName": "Catppuccin Frappé",
    "type": "dark",
    "foreground": "#C6D0F5",
    "background": "#303446"
  },
  {
    "id": "catppuccin-latte",
    "displayName": "Catppuccin Latte",
    "type": "light",
    "foreground": "#4C4F69",
    "background": "#EFF1F5"
  },
  {
    "id": "catppuccin-macchiato",
    "displayName": "Catppuccin Macchiato",
    "type": "dark",
    "foreground": "#CAD3F5",
    "background": "#24273A"
  },
  {
    "id": "catppuccin-mocha",
    "displayName": "Catppuccin Mocha",
    "type": "dark",
    "foreground": "#CDD6F4",
    "background": "#1E1E2E"
  },
  {
    "id": "dark-plus",
    "displayName": "Dark Plus",
    "type": "dark",
    "foreground": "#D4D4D4",
    "background": "#1E1E1E"
  },
  {
    "id": "dracula",
    "displayName": "Dracula Theme",
    "type": "dark",
    "foreground": "#F8F8F2",
    "background": "#282A36"
  },
  {
    "id": "dracula-soft",
    "displayName": "Dracula Theme Soft",
    "type": "dark",
    "foreground": "#F6F6F4",
    "background": "#282A36"
  },
  {
    "id": "everforest-dark",
    "displayName": "Everforest Dark",
    "type": "dark",
    "foreground": "#D3C6AA",
    "background": "#2D353B"
  },
  {
    "id": "everforest-light",
    "displayName": "Everforest Light",
    "type": "light",
    "foreground": "#5C6A72",
    "background": "#FDF6E3"
  },
  {
    "id": "github-dark",
    "displayName": "GitHub Dark",
    "type": "dark",
    "foreground": "#E1E4E8",
    "background": "#24292E"
  },
  {
    "id": "github-dark-default",
    "displayName": "GitHub Dark Default",
    "type": "dark",
    "foreground": "#E6EDF3",
    "background": "#0D1117"
  },
  {
    "id": "github-dark-dimmed",
    "displayName": "GitHub Dark Dimmed",
    "type": "dark",
    "foreground": "#ADBAC7",
    "background": "#22272E"
  },
  {
    "id": "github-dark-high-contrast",
    "displayName": "GitHub Dark High Contrast",
    "type": "dark",
    "foreground": "#F0F3F6",
    "background": "#0A0C10"
  },
  {
    "id": "github-light",
    "displayName": "GitHub Light",
    "type": "light",
    "foreground": "#24292E",
    "background": "#FFFFFF"
  },
  {
    "id": "github-light-default",
    "displayName": "GitHub Light Default",
    "type": "light",
    "foreground": "#1F2328",
    "background": "#FFFFFF"
  },
  {
    "id": "github-light-high-contrast",
    "displayName": "GitHub Light High Contrast",
    "type": "light",
    "foreground": "#0E1116",
    "background": "#FFFFFF"
  },
  {
    "id": "gruvbox-dark-hard",
    "displayName": "Gruvbox Dark Hard",
    "type": "dark",
    "foreground": "#EBDBB2",
    "background": "#1D2021"
  },
  {
    "id": "gruvbox-dark-medium",
    "displayName": "Gruvbox Dark Medium",
    "type": "dark",
    "foreground": "#EBDBB2",
    "background": "#282828"
  },
  {
    "id": "gruvbox-dark-soft",
    "displayName": "Gruvbox Dark Soft",
    "type": "dark",
    "foreground": "#EBDBB2",
    "background": "#32302F"
  },
  {
    "id": "gruvbox-light-hard",
    "displayName": "Gruvbox Light Hard",
    "type": "light",
    "foreground": "#3C3836",
    "background": "#F9F5D7"
  },
  {
    "id": "gruvbox-light-medium",
    "displayName": "Gruvbox Light Medium",
    "type": "light",
    "foreground": "#3C3836",
    "background": "#FBF1C7"
  },
  {
    "id": "gruvbox-light-soft",
    "displayName": "Gruvbox Light Soft",
    "type": "light",
    "foreground": "#3C3836",
    "background": "#F2E5BC"
  },
  {
    "id": "horizon",
    "displayName": "Horizon",
    "type": "dark",
    "foreground": "#BBBBBB",
    "background": "#1C1E26"
  },
  {
    "id": "horizon-bright",
    "displayName": "Horizon Bright",
    "type": "light",
    "foreground": "#333333",
    "background": "#FDF0ED"
  },
  {
    "id": "houston",
    "displayName": "Houston",
    "type": "dark",
    "foreground": "#EEF0F9",
    "background": "#17191E"
  },
  {
    "id": "kanagawa-dragon",
    "displayName": "Kanagawa Dragon",
    "type": "dark",
    "foreground": "#C5C9C5",
    "background": "#181616"
  },
  {
    "id": "kanagawa-lotus",
    "displayName": "Kanagawa Lotus",
    "type": "light",
    "foreground": "#545464",
    "background": "#F2ECBC"
  },
  {
    "id": "kanagawa-wave",
    "displayName": "Kanagawa Wave",
    "type": "dark",
    "foreground": "#DCD7BA",
    "background": "#1F1F28"
  },
  {
    "id": "laserwave",
    "displayName": "LaserWave",
    "type": "dark",
    "foreground": "#FFFFFF",
    "background": "#27212E"
  },
  {
    "id": "light-plus",
    "displayName": "Light Plus",
    "type": "light",
    "foreground": "#000000",
    "background": "#FFFFFF"
  },
  {
    "id": "material-theme",
    "displayName": "Material Theme",
    "type": "dark",
    "foreground": "#EEFFFF",
    "background": "#263238"
  },
  {
    "id": "material-theme-darker",
    "displayName": "Material Theme Darker",
    "type": "dark",
    "foreground": "#EEFFFF",
    "background": "#212121"
  },
  {
    "id": "material-theme-lighter",
    "displayName": "Material Theme Lighter",
    "type": "light",
    "foreground": "#90A4AE",
    "background": "#FAFAFA"
  },
  {
    "id": "material-theme-ocean",
    "displayName": "Material Theme Ocean",
    "type": "dark",
    "foreground": "#BABED8",
    "background": "#0F111A"
  },
  {
    "id": "material-theme-palenight",
    "displayName": "Material Theme Palenight",
    "type": "dark",
    "foreground": "#BABED8",
    "background": "#292D3E"
  },
  {
    "id": "min-dark",
    "displayName": "Min Dark",
    "type": "dark",
    "foreground": "#B392F0",
    "background": "#1F1F1F"
  },
  {
    "id": "min-light",
    "displayName": "Min Light",
    "type": "light",
    "foreground": "#24292E",
    "background": "#FFFFFF"
  },
  {
    "id": "monokai",
    "displayName": "Monokai",
    "type": "dark",
    "foreground": "#F8F8F2",
    "background": "#272822"
  },
  {
    "id": "night-owl",
    "displayName": "Night Owl",
    "type": "dark",
    "foreground": "#D6DEEB",
    "background": "#011627"
  },
  {
    "id": "night-owl-light",
    "displayName": "Night Owl Light",
    "type": "light",
    "foreground": "#403F53",
    "background": "#FBFBFB"
  },
  {
    "id": "nord",
    "displayName": "Nord",
    "type": "dark",
    "foreground": "#D8DEE9",
    "background": "#2E3440"
  },
  {
    "id": "one-dark-pro",
    "displayName": "One Dark Pro",
    "type": "dark",
    "foreground": "#ABB2BF",
    "background": "#282C34"
  },
  {
    "id": "one-light",
    "displayName": "One Light",
    "type": "light",
    "foreground": "#383A42",
    "background": "#FAFAFA"
  },
  {
    "id": "plastic",
    "displayName": "Plastic",
    "type": "dark",
    "foreground": "#A9B2C3",
    "background": "#21252B"
  },
  {
    "id": "poimandres",
    "displayName": "Poimandres",
    "type": "dark",
    "foreground": "#A6ACCD",
    "background": "#1B1E28"
  },
  {
    "id": "red",
    "displayName": "Red",
    "type": "dark",
    "foreground": "#F8F8F8",
    "background": "#390000"
  },
  {
    "id": "rose-pine",
    "displayName": "Rosé Pine",
    "type": "dark",
    "foreground": "#E0DEF4",
    "background": "#191724"
  },
  {
    "id": "rose-pine-dawn",
    "displayName": "Rosé Pine Dawn",
    "type": "light",
    "foreground": "#575279",
    "background": "#FAF4ED"
  },
  {
    "id": "rose-pine-moon",
    "displayName": "Rosé Pine Moon",
    "type": "dark",
    "foreground": "#E0DEF4",
    "background": "#232136"
  },
  {
    "id": "slack-dark",
    "displayName": "Slack Dark",
    "type": "dark",
    "foreground": "#E6E6E6",
    "background": "#222222"
  },
  {
    "id": "slack-ochin",
    "displayName": "Slack Ochin",
    "type": "light",
    "foreground": "#002339",
    "background": "#FFFFFF"
  },
  {
    "id": "snazzy-light",
    "displayName": "Snazzy Light",
    "type": "light",
    "foreground": "#565869",
    "background": "#FAFBFC"
  },
  {
    "id": "solarized-dark",
    "displayName": "Solarized Dark",
    "type": "dark",
    "foreground": "#839496",
    "background": "#002B36"
  },
  {
    "id": "solarized-light",
    "displayName": "Solarized Light",
    "type": "light",
    "foreground": "#657B83",
    "background": "#FDF6E3"
  },
  {
    "id": "synthwave-84",
    "displayName": "Synthwave '84",
    "type": "dark",
    "foreground": "#BBBBBB",
    "background": "#262335"
  },
  {
    "id": "tokyo-night",
    "displayName": "Tokyo Night",
    "type": "dark",
    "foreground": "#A9B1D6",
    "background": "#1A1B26"
  },
  {
    "id": "vesper",
    "displayName": "Vesper",
    "type": "dark",
    "foreground": "#FFFFFF",
    "background": "#101010"
  },
  {
    "id": "vitesse-black",
    "displayName": "Vitesse Black",
    "type": "dark",
    "foreground": "#DBD7CA",
    "background": "#000000"
  },
  {
    "id": "vitesse-dark",
    "displayName": "Vitesse Dark",
    "type": "dark",
    "foreground": "#DBD7CA",
    "background": "#121212"
  },
  {
    "id": "vitesse-light",
    "displayName": "Vitesse Light",
    "type": "light",
    "foreground": "#393A34",
    "background": "#FFFFFF"
  }
] as const;

export const CODE_LANGUAGES = [
  {
    "id": "abap",
    "name": "ABAP",
    "aliases": []
  },
  {
    "id": "actionscript-3",
    "name": "ActionScript",
    "aliases": []
  },
  {
    "id": "ada",
    "name": "Ada",
    "aliases": []
  },
  {
    "id": "angular-html",
    "name": "Angular HTML",
    "aliases": []
  },
  {
    "id": "angular-ts",
    "name": "Angular TypeScript",
    "aliases": []
  },
  {
    "id": "apache",
    "name": "Apache Conf",
    "aliases": []
  },
  {
    "id": "apex",
    "name": "Apex",
    "aliases": []
  },
  {
    "id": "apl",
    "name": "APL",
    "aliases": []
  },
  {
    "id": "applescript",
    "name": "AppleScript",
    "aliases": []
  },
  {
    "id": "ara",
    "name": "Ara",
    "aliases": []
  },
  {
    "id": "asciidoc",
    "name": "AsciiDoc",
    "aliases": [
      "adoc"
    ]
  },
  {
    "id": "asm",
    "name": "Assembly",
    "aliases": []
  },
  {
    "id": "astro",
    "name": "Astro",
    "aliases": []
  },
  {
    "id": "awk",
    "name": "AWK",
    "aliases": []
  },
  {
    "id": "ballerina",
    "name": "Ballerina",
    "aliases": []
  },
  {
    "id": "bat",
    "name": "Batch File",
    "aliases": [
      "batch"
    ]
  },
  {
    "id": "beancount",
    "name": "Beancount",
    "aliases": []
  },
  {
    "id": "berry",
    "name": "Berry",
    "aliases": [
      "be"
    ]
  },
  {
    "id": "bibtex",
    "name": "BibTeX",
    "aliases": []
  },
  {
    "id": "bicep",
    "name": "Bicep",
    "aliases": []
  },
  {
    "id": "bird2",
    "name": "BIRD2 Configuration",
    "aliases": [
      "bird"
    ]
  },
  {
    "id": "blade",
    "name": "Blade",
    "aliases": []
  },
  {
    "id": "bsl",
    "name": "1C (Enterprise)",
    "aliases": [
      "1c"
    ]
  },
  {
    "id": "c",
    "name": "C",
    "aliases": []
  },
  {
    "id": "c3",
    "name": "C3",
    "aliases": []
  },
  {
    "id": "cadence",
    "name": "Cadence",
    "aliases": [
      "cdc"
    ]
  },
  {
    "id": "cairo",
    "name": "Cairo",
    "aliases": []
  },
  {
    "id": "clarity",
    "name": "Clarity",
    "aliases": []
  },
  {
    "id": "clojure",
    "name": "Clojure",
    "aliases": [
      "clj"
    ]
  },
  {
    "id": "cmake",
    "name": "CMake",
    "aliases": []
  },
  {
    "id": "cobol",
    "name": "COBOL",
    "aliases": []
  },
  {
    "id": "codeowners",
    "name": "CODEOWNERS",
    "aliases": []
  },
  {
    "id": "codeql",
    "name": "CodeQL",
    "aliases": [
      "ql"
    ]
  },
  {
    "id": "coffee",
    "name": "CoffeeScript",
    "aliases": [
      "coffeescript"
    ]
  },
  {
    "id": "common-lisp",
    "name": "Common Lisp",
    "aliases": [
      "lisp"
    ]
  },
  {
    "id": "coq",
    "name": "Coq",
    "aliases": []
  },
  {
    "id": "cpp",
    "name": "C++",
    "aliases": [
      "c++"
    ]
  },
  {
    "id": "crystal",
    "name": "Crystal",
    "aliases": []
  },
  {
    "id": "csharp",
    "name": "C#",
    "aliases": [
      "c#",
      "cs"
    ]
  },
  {
    "id": "css",
    "name": "CSS",
    "aliases": []
  },
  {
    "id": "csv",
    "name": "CSV",
    "aliases": []
  },
  {
    "id": "cue",
    "name": "CUE",
    "aliases": []
  },
  {
    "id": "cypher",
    "name": "Cypher",
    "aliases": [
      "cql"
    ]
  },
  {
    "id": "d",
    "name": "D",
    "aliases": []
  },
  {
    "id": "dart",
    "name": "Dart",
    "aliases": []
  },
  {
    "id": "dax",
    "name": "DAX",
    "aliases": []
  },
  {
    "id": "desktop",
    "name": "Desktop",
    "aliases": []
  },
  {
    "id": "diff",
    "name": "Diff",
    "aliases": []
  },
  {
    "id": "docker",
    "name": "Dockerfile",
    "aliases": [
      "dockerfile"
    ]
  },
  {
    "id": "dotenv",
    "name": "dotEnv",
    "aliases": []
  },
  {
    "id": "dream-maker",
    "name": "Dream Maker",
    "aliases": []
  },
  {
    "id": "edge",
    "name": "Edge",
    "aliases": []
  },
  {
    "id": "elixir",
    "name": "Elixir",
    "aliases": []
  },
  {
    "id": "elm",
    "name": "Elm",
    "aliases": []
  },
  {
    "id": "emacs-lisp",
    "name": "Emacs Lisp",
    "aliases": [
      "elisp"
    ]
  },
  {
    "id": "erb",
    "name": "ERB",
    "aliases": []
  },
  {
    "id": "erlang",
    "name": "Erlang",
    "aliases": [
      "erl"
    ]
  },
  {
    "id": "fennel",
    "name": "Fennel",
    "aliases": []
  },
  {
    "id": "fish",
    "name": "Fish",
    "aliases": []
  },
  {
    "id": "fluent",
    "name": "Fluent",
    "aliases": [
      "ftl"
    ]
  },
  {
    "id": "fortran-fixed-form",
    "name": "Fortran (Fixed Form)",
    "aliases": [
      "f",
      "f77",
      "for"
    ]
  },
  {
    "id": "fortran-free-form",
    "name": "Fortran (Free Form)",
    "aliases": [
      "f03",
      "f08",
      "f18",
      "f90",
      "f95"
    ]
  },
  {
    "id": "fsharp",
    "name": "F#",
    "aliases": [
      "f#",
      "fs"
    ]
  },
  {
    "id": "gdresource",
    "name": "GDResource",
    "aliases": [
      "tres",
      "tscn"
    ]
  },
  {
    "id": "gdscript",
    "name": "GDScript",
    "aliases": [
      "gd"
    ]
  },
  {
    "id": "gdshader",
    "name": "GDShader",
    "aliases": []
  },
  {
    "id": "genie",
    "name": "Genie",
    "aliases": []
  },
  {
    "id": "gherkin",
    "name": "Gherkin",
    "aliases": []
  },
  {
    "id": "git-commit",
    "name": "Git Commit Message",
    "aliases": []
  },
  {
    "id": "git-rebase",
    "name": "Git Rebase Message",
    "aliases": []
  },
  {
    "id": "gleam",
    "name": "Gleam",
    "aliases": []
  },
  {
    "id": "glimmer-js",
    "name": "Glimmer JS",
    "aliases": [
      "gjs"
    ]
  },
  {
    "id": "glimmer-ts",
    "name": "Glimmer TS",
    "aliases": [
      "gts"
    ]
  },
  {
    "id": "glsl",
    "name": "GLSL",
    "aliases": []
  },
  {
    "id": "gn",
    "name": "GN",
    "aliases": []
  },
  {
    "id": "gnuplot",
    "name": "Gnuplot",
    "aliases": []
  },
  {
    "id": "go",
    "name": "Go",
    "aliases": []
  },
  {
    "id": "graphql",
    "name": "GraphQL",
    "aliases": [
      "gql"
    ]
  },
  {
    "id": "groovy",
    "name": "Groovy",
    "aliases": []
  },
  {
    "id": "hack",
    "name": "Hack",
    "aliases": []
  },
  {
    "id": "haml",
    "name": "Ruby Haml",
    "aliases": []
  },
  {
    "id": "handlebars",
    "name": "Handlebars",
    "aliases": [
      "hbs"
    ]
  },
  {
    "id": "haskell",
    "name": "Haskell",
    "aliases": [
      "hs"
    ]
  },
  {
    "id": "haxe",
    "name": "Haxe",
    "aliases": []
  },
  {
    "id": "hcl",
    "name": "HashiCorp HCL",
    "aliases": []
  },
  {
    "id": "hjson",
    "name": "Hjson",
    "aliases": []
  },
  {
    "id": "hlsl",
    "name": "HLSL",
    "aliases": []
  },
  {
    "id": "html",
    "name": "HTML",
    "aliases": []
  },
  {
    "id": "html-derivative",
    "name": "HTML (Derivative)",
    "aliases": []
  },
  {
    "id": "http",
    "name": "HTTP",
    "aliases": []
  },
  {
    "id": "hurl",
    "name": "Hurl",
    "aliases": []
  },
  {
    "id": "hxml",
    "name": "HXML",
    "aliases": []
  },
  {
    "id": "hy",
    "name": "Hy",
    "aliases": []
  },
  {
    "id": "imba",
    "name": "Imba",
    "aliases": []
  },
  {
    "id": "ini",
    "name": "INI",
    "aliases": [
      "properties"
    ]
  },
  {
    "id": "java",
    "name": "Java",
    "aliases": []
  },
  {
    "id": "javascript",
    "name": "JavaScript",
    "aliases": [
      "cjs",
      "js",
      "mjs"
    ]
  },
  {
    "id": "jinja",
    "name": "Jinja",
    "aliases": []
  },
  {
    "id": "jison",
    "name": "Jison",
    "aliases": []
  },
  {
    "id": "json",
    "name": "JSON",
    "aliases": []
  },
  {
    "id": "json5",
    "name": "JSON5",
    "aliases": []
  },
  {
    "id": "jsonc",
    "name": "JSON with Comments",
    "aliases": []
  },
  {
    "id": "jsonl",
    "name": "JSON Lines",
    "aliases": []
  },
  {
    "id": "jsonnet",
    "name": "Jsonnet",
    "aliases": []
  },
  {
    "id": "jssm",
    "name": "JSSM",
    "aliases": [
      "fsl"
    ]
  },
  {
    "id": "jsx",
    "name": "JSX",
    "aliases": []
  },
  {
    "id": "julia",
    "name": "Julia",
    "aliases": [
      "jl"
    ]
  },
  {
    "id": "just",
    "name": "Just",
    "aliases": []
  },
  {
    "id": "kdl",
    "name": "KDL",
    "aliases": []
  },
  {
    "id": "kotlin",
    "name": "Kotlin",
    "aliases": [
      "kt",
      "kts"
    ]
  },
  {
    "id": "kusto",
    "name": "Kusto",
    "aliases": [
      "kql"
    ]
  },
  {
    "id": "latex",
    "name": "LaTeX",
    "aliases": []
  },
  {
    "id": "lean",
    "name": "Lean 4",
    "aliases": [
      "lean4"
    ]
  },
  {
    "id": "less",
    "name": "Less",
    "aliases": []
  },
  {
    "id": "liquid",
    "name": "Liquid",
    "aliases": []
  },
  {
    "id": "llvm",
    "name": "LLVM IR",
    "aliases": []
  },
  {
    "id": "log",
    "name": "Log file",
    "aliases": []
  },
  {
    "id": "logo",
    "name": "Logo",
    "aliases": []
  },
  {
    "id": "lua",
    "name": "Lua",
    "aliases": []
  },
  {
    "id": "luau",
    "name": "Luau",
    "aliases": []
  },
  {
    "id": "make",
    "name": "Makefile",
    "aliases": [
      "makefile"
    ]
  },
  {
    "id": "markdown",
    "name": "Markdown",
    "aliases": [
      "md"
    ]
  },
  {
    "id": "marko",
    "name": "Marko",
    "aliases": []
  },
  {
    "id": "matlab",
    "name": "MATLAB",
    "aliases": []
  },
  {
    "id": "mdc",
    "name": "MDC",
    "aliases": []
  },
  {
    "id": "mdx",
    "name": "MDX",
    "aliases": []
  },
  {
    "id": "mermaid",
    "name": "Mermaid",
    "aliases": [
      "mmd"
    ]
  },
  {
    "id": "mipsasm",
    "name": "MIPS Assembly",
    "aliases": [
      "mips"
    ]
  },
  {
    "id": "mojo",
    "name": "Mojo",
    "aliases": []
  },
  {
    "id": "moonbit",
    "name": "MoonBit",
    "aliases": [
      "mbt",
      "mbti"
    ]
  },
  {
    "id": "move",
    "name": "Move",
    "aliases": []
  },
  {
    "id": "narrat",
    "name": "Narrat Language",
    "aliases": [
      "nar"
    ]
  },
  {
    "id": "nextflow",
    "name": "Nextflow",
    "aliases": [
      "nf"
    ]
  },
  {
    "id": "nextflow-groovy",
    "name": "Nextflow Groovy",
    "aliases": []
  },
  {
    "id": "nginx",
    "name": "Nginx",
    "aliases": []
  },
  {
    "id": "nim",
    "name": "Nim",
    "aliases": []
  },
  {
    "id": "nix",
    "name": "Nix",
    "aliases": []
  },
  {
    "id": "nushell",
    "name": "nushell",
    "aliases": [
      "nu"
    ]
  },
  {
    "id": "objective-c",
    "name": "Objective-C",
    "aliases": [
      "objc"
    ]
  },
  {
    "id": "objective-cpp",
    "name": "Objective-C++",
    "aliases": []
  },
  {
    "id": "ocaml",
    "name": "OCaml",
    "aliases": []
  },
  {
    "id": "odin",
    "name": "Odin",
    "aliases": []
  },
  {
    "id": "openscad",
    "name": "OpenSCAD",
    "aliases": [
      "scad"
    ]
  },
  {
    "id": "pascal",
    "name": "Pascal",
    "aliases": []
  },
  {
    "id": "perl",
    "name": "Perl",
    "aliases": []
  },
  {
    "id": "php",
    "name": "PHP",
    "aliases": []
  },
  {
    "id": "pkl",
    "name": "Pkl",
    "aliases": []
  },
  {
    "id": "plsql",
    "name": "PL/SQL",
    "aliases": []
  },
  {
    "id": "po",
    "name": "Gettext PO",
    "aliases": [
      "pot",
      "potx"
    ]
  },
  {
    "id": "polar",
    "name": "Polar",
    "aliases": []
  },
  {
    "id": "postcss",
    "name": "PostCSS",
    "aliases": []
  },
  {
    "id": "powerquery",
    "name": "PowerQuery",
    "aliases": []
  },
  {
    "id": "powershell",
    "name": "PowerShell",
    "aliases": [
      "ps",
      "ps1"
    ]
  },
  {
    "id": "prisma",
    "name": "Prisma",
    "aliases": []
  },
  {
    "id": "prolog",
    "name": "Prolog",
    "aliases": []
  },
  {
    "id": "proto",
    "name": "Protocol Buffer 3",
    "aliases": [
      "protobuf"
    ]
  },
  {
    "id": "pug",
    "name": "Pug",
    "aliases": [
      "jade"
    ]
  },
  {
    "id": "puppet",
    "name": "Puppet",
    "aliases": []
  },
  {
    "id": "purescript",
    "name": "PureScript",
    "aliases": []
  },
  {
    "id": "python",
    "name": "Python",
    "aliases": [
      "py"
    ]
  },
  {
    "id": "qml",
    "name": "QML",
    "aliases": []
  },
  {
    "id": "qmldir",
    "name": "QML Directory",
    "aliases": []
  },
  {
    "id": "qss",
    "name": "Qt Style Sheets",
    "aliases": []
  },
  {
    "id": "r",
    "name": "R",
    "aliases": []
  },
  {
    "id": "racket",
    "name": "Racket",
    "aliases": []
  },
  {
    "id": "raku",
    "name": "Raku",
    "aliases": [
      "perl6"
    ]
  },
  {
    "id": "razor",
    "name": "ASP.NET Razor",
    "aliases": []
  },
  {
    "id": "reg",
    "name": "Windows Registry Script",
    "aliases": []
  },
  {
    "id": "regexp",
    "name": "RegExp",
    "aliases": [
      "regex"
    ]
  },
  {
    "id": "rel",
    "name": "Rel",
    "aliases": []
  },
  {
    "id": "riscv",
    "name": "RISC-V",
    "aliases": []
  },
  {
    "id": "ron",
    "name": "RON",
    "aliases": []
  },
  {
    "id": "rosmsg",
    "name": "ROS Interface",
    "aliases": []
  },
  {
    "id": "rst",
    "name": "reStructuredText",
    "aliases": []
  },
  {
    "id": "ruby",
    "name": "Ruby",
    "aliases": [
      "rb"
    ]
  },
  {
    "id": "rust",
    "name": "Rust",
    "aliases": [
      "rs"
    ]
  },
  {
    "id": "sas",
    "name": "SAS",
    "aliases": []
  },
  {
    "id": "sass",
    "name": "Sass",
    "aliases": []
  },
  {
    "id": "scala",
    "name": "Scala",
    "aliases": []
  },
  {
    "id": "scheme",
    "name": "Scheme",
    "aliases": []
  },
  {
    "id": "scss",
    "name": "SCSS",
    "aliases": []
  },
  {
    "id": "sdbl",
    "name": "1C (Query)",
    "aliases": [
      "1c-query"
    ]
  },
  {
    "id": "shaderlab",
    "name": "ShaderLab",
    "aliases": [
      "shader"
    ]
  },
  {
    "id": "shellscript",
    "name": "Shell",
    "aliases": [
      "bash",
      "sh",
      "shell",
      "zsh"
    ]
  },
  {
    "id": "shellsession",
    "name": "Shell Session",
    "aliases": [
      "console"
    ]
  },
  {
    "id": "smalltalk",
    "name": "Smalltalk",
    "aliases": []
  },
  {
    "id": "solidity",
    "name": "Solidity",
    "aliases": []
  },
  {
    "id": "soy",
    "name": "Closure Templates",
    "aliases": [
      "closure-templates"
    ]
  },
  {
    "id": "sparql",
    "name": "SPARQL",
    "aliases": []
  },
  {
    "id": "splunk",
    "name": "Splunk Query Language",
    "aliases": [
      "spl"
    ]
  },
  {
    "id": "sql",
    "name": "SQL",
    "aliases": []
  },
  {
    "id": "ssh-config",
    "name": "SSH Config",
    "aliases": []
  },
  {
    "id": "stata",
    "name": "Stata",
    "aliases": []
  },
  {
    "id": "stylus",
    "name": "Stylus",
    "aliases": [
      "styl"
    ]
  },
  {
    "id": "surrealql",
    "name": "SurrealQL",
    "aliases": [
      "surql"
    ]
  },
  {
    "id": "svelte",
    "name": "Svelte",
    "aliases": []
  },
  {
    "id": "swift",
    "name": "Swift",
    "aliases": []
  },
  {
    "id": "system-verilog",
    "name": "SystemVerilog",
    "aliases": []
  },
  {
    "id": "systemd",
    "name": "Systemd Units",
    "aliases": []
  },
  {
    "id": "talonscript",
    "name": "TalonScript",
    "aliases": [
      "talon"
    ]
  },
  {
    "id": "tasl",
    "name": "Tasl",
    "aliases": []
  },
  {
    "id": "tcl",
    "name": "Tcl",
    "aliases": []
  },
  {
    "id": "templ",
    "name": "Templ",
    "aliases": []
  },
  {
    "id": "terraform",
    "name": "Terraform",
    "aliases": [
      "tf",
      "tfvars"
    ]
  },
  {
    "id": "tex",
    "name": "TeX",
    "aliases": []
  },
  {
    "id": "toml",
    "name": "TOML",
    "aliases": []
  },
  {
    "id": "ts-tags",
    "name": "TypeScript with Tags",
    "aliases": [
      "lit"
    ]
  },
  {
    "id": "tsv",
    "name": "TSV",
    "aliases": []
  },
  {
    "id": "tsx",
    "name": "TSX",
    "aliases": []
  },
  {
    "id": "turtle",
    "name": "Turtle",
    "aliases": []
  },
  {
    "id": "twig",
    "name": "Twig",
    "aliases": []
  },
  {
    "id": "typescript",
    "name": "TypeScript",
    "aliases": [
      "cts",
      "mts",
      "ts"
    ]
  },
  {
    "id": "typespec",
    "name": "TypeSpec",
    "aliases": [
      "tsp"
    ]
  },
  {
    "id": "typst",
    "name": "Typst",
    "aliases": [
      "typ"
    ]
  },
  {
    "id": "v",
    "name": "V",
    "aliases": []
  },
  {
    "id": "vala",
    "name": "Vala",
    "aliases": []
  },
  {
    "id": "vb",
    "name": "Visual Basic",
    "aliases": [
      "cmd"
    ]
  },
  {
    "id": "verilog",
    "name": "Verilog",
    "aliases": []
  },
  {
    "id": "vhdl",
    "name": "VHDL",
    "aliases": []
  },
  {
    "id": "viml",
    "name": "Vim Script",
    "aliases": [
      "vim",
      "vimscript"
    ]
  },
  {
    "id": "vue",
    "name": "Vue",
    "aliases": []
  },
  {
    "id": "vue-html",
    "name": "Vue HTML",
    "aliases": []
  },
  {
    "id": "vue-vine",
    "name": "Vue Vine",
    "aliases": []
  },
  {
    "id": "vyper",
    "name": "Vyper",
    "aliases": [
      "vy"
    ]
  },
  {
    "id": "wasm",
    "name": "WebAssembly",
    "aliases": []
  },
  {
    "id": "wenyan",
    "name": "Wenyan",
    "aliases": [
      "文言"
    ]
  },
  {
    "id": "wgsl",
    "name": "WGSL",
    "aliases": []
  },
  {
    "id": "wikitext",
    "name": "Wikitext",
    "aliases": [
      "mediawiki",
      "wiki"
    ]
  },
  {
    "id": "wit",
    "name": "WebAssembly Interface Types",
    "aliases": []
  },
  {
    "id": "wolfram",
    "name": "Wolfram",
    "aliases": [
      "wl"
    ]
  },
  {
    "id": "xml",
    "name": "XML",
    "aliases": []
  },
  {
    "id": "xsl",
    "name": "XSL",
    "aliases": []
  },
  {
    "id": "yaml",
    "name": "YAML",
    "aliases": [
      "yml"
    ]
  },
  {
    "id": "zenscript",
    "name": "ZenScript",
    "aliases": []
  },
  {
    "id": "zig",
    "name": "Zig",
    "aliases": []
  }
] as const;
