import { describe, expect, test } from "bun:test";
import { readdirSync, readFileSync } from "node:fs";
import { basename, extname, resolve } from "node:path";
import { unzipDocx } from "@atlcli/docx/scan";
import {
  analyzeFixture,
  canonicalJson,
  type FixtureAnalysisV1,
} from "../fixture-analysis.js";
import {
  renderTemplateIntakeMessage,
  TEMPLATE_INTAKE_MESSAGES_V1,
  type MessageParameterSchemaV1,
  type TemplateIntakeMessageCode,
} from "../messages.js";

const FIXTURES_DIRECTORY = import.meta.dir;
const GOLDENS_DIRECTORY = resolve(FIXTURES_DIRECTORY, "goldens");
const UX_DIRECTORY = resolve(FIXTURES_DIRECTORY, "ux");
const README = readFileSync(resolve(FIXTURES_DIRECTORY, "README.md"), "utf8");
const BINARY_FIXTURES = [
  "neutral-generated-python-docx-1.2.0.docx",
  "neutral-word-16.111.1.docx",
  "neutral-libreoffice-7.1.1.2.docx",
] as const;

const PERMITTED_MARKERS = [
  "NEUTRAL_FIXTURE_TITLE",
  "NEUTRAL_FIXTURE_SUBTITLE",
  "NEUTRAL_HEADING_ONE",
  "NEUTRAL_HEADING_TWO",
  "NEUTRAL_HEADING_THREE",
  "NEUTRAL_BODY_ALPHA",
  "NEUTRAL_BODY_BETA",
  "NEUTRAL_CODE_SAMPLE",
  "NEUTRAL_CAPTION",
  "NEUTRAL_TABLE_HEADER_A",
  "NEUTRAL_TABLE_HEADER_B",
  "NEUTRAL_TABLE_CELL_A",
  "NEUTRAL_TABLE_CELL_B",
  "NEUTRAL_HEADER_DEFAULT",
  "NEUTRAL_HEADER_FIRST",
  "NEUTRAL_HEADER_EVEN",
  "NEUTRAL_FOOTER",
  "NEUTRAL_SECTION_TWO",
  "ATLCLI_SYNTHETIC_FIXTURE",
] as const;

const PERMITTED_METADATA = new Set([
  "",
  "ATLCLI Synthetic Fixture",
  "ATLCLI_SYNTHETIC_FIXTURE",
  "Neutral DOCX Template Fixture",
  "generated by python-docx",
]);

function analysisFor(fixture: (typeof BINARY_FIXTURES)[number]): FixtureAnalysisV1 {
  return analyzeFixture(fixture, readFileSync(resolve(FIXTURES_DIRECTORY, fixture)));
}

function decodeXmlText(value: string): string {
  return value
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .trim();
}

function extractContentValues(xml: string): string[] {
  const values: string[] = [];
  for (const match of xml.matchAll(/<w:t\b[^>]*>([\s\S]*?)<\/w:t>/g)) {
    values.push(decodeXmlText(match[1]));
  }
  for (const match of xml.matchAll(
    /<(dc:title|dc:subject|dc:creator|dc:description|cp:lastModifiedBy|cp:keywords)\b[^>]*>([\s\S]*?)<\/\1>/g
  )) {
    values.push(decodeXmlText(match[2]));
  }
  return values;
}

function listTextFiles(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = resolve(directory, entry.name);
    return entry.isDirectory() ? listTextFiles(path) : [path];
  });
}

function expectNoPrivateMaterial(label: string, value: string): void {
  expect(value, `${label} contains an absolute user path`).not.toMatch(
    /(?:\/Users\/|[A-Za-z]:\\Users\\)/
  );
  expect(value, `${label} contains an Atlassian tenant URL`).not.toMatch(/\.atlassian\.net\b/i);
  expect(value, `${label} contains an account or tenant identifier key`).not.toMatch(
    /\b(?:accountId|cloudId|tenantId)\b/i
  );
  expect(value, `${label} contains an email address`).not.toMatch(
    /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/i
  );

  const configuredDenylist = (process.env.ATLCLI_FIXTURE_PROHIBITED_TERMS ?? "")
    .split(",")
    .map((term) => term.trim())
    .filter(Boolean);
  for (const prohibited of configuredDenylist) {
    expect(
      value.toLocaleLowerCase(),
      `${label} contains a configured prohibited term`
    ).not.toContain(prohibited.toLocaleLowerCase());
  }
}

function allKeys(value: unknown): string[] {
  if (Array.isArray(value)) return value.flatMap(allKeys);
  if (!value || typeof value !== "object") return [];
  return Object.entries(value).flatMap(([key, child]) => [key, ...allKeys(child)]);
}

describe("T0 neutral fixture contract", () => {
  test("README freezes provenance, versions, features, hashes, and every marker", () => {
    expect(README).toContain("Python 3.14.2");
    expect(README).toContain("python-docx 1.2.0");
    expect(README).toContain("Pillow 12.2.0");
    expect(README).toContain("Microsoft Word for Mac 16.111.1");
    expect(README).toContain("LibreOffice 7.1.1.2");
    expect(README).toContain("Expected OOXML features");

    for (const marker of PERMITTED_MARKERS) expect(README).toContain(`\`${marker}\``);
    for (const fixture of BINARY_FIXTURES) {
      const analysis = analysisFor(fixture);
      expect(README).toContain(`\`${fixture}\``);
      expect(README).toContain(`\`${analysis.sha256}\``);
    }
  });

  test("binary structure is reproduced exactly by text-free analysis goldens", () => {
    for (const fixture of BINARY_FIXTURES) {
      const actual = analysisFor(fixture);
      const goldenPath = resolve(
        GOLDENS_DIRECTORY,
        `${basename(fixture, ".docx")}.analysis.json`
      );
      const expectedText = readFileSync(goldenPath, "utf8");
      expect(canonicalJson(actual)).toBe(expectedText);
      expect(allKeys(actual)).not.toContain("text");
      expect(allKeys(actual)).not.toContain("content");
      expect(allKeys(actual)).not.toContain("altText");
      for (const marker of PERMITTED_MARKERS) expect(expectedText).not.toContain(marker);
    }
  });

  test("fixture and golden files contain only synthetic content and safe format URLs", () => {
    const observedMarkers = new Set<string>();
    const allowedUrlPrefixes = [
      "http://purl.org/",
      "http://schemas.microsoft.com/",
      "http://schemas.openxmlformats.org/",
      "http://www.w3.org/",
      "https://json-schema.org/",
    ];

    for (const fixture of BINARY_FIXTURES) {
      const zip = unzipDocx(readFileSync(resolve(FIXTURES_DIRECTORY, fixture)));
      for (const entry of Object.values(zip.files)) {
        if (entry.dir || !/(\.xml|\.rels)$/i.test(entry.name)) continue;
        const xml = entry.asText();
        expectNoPrivateMaterial(`${fixture}:${entry.name}`, xml);
        for (const match of xml.matchAll(/(?:https?|file):\/\/[^"' <>\s]+/g)) {
          expect(
            allowedUrlPrefixes.some((prefix) => match[0].startsWith(prefix)),
            `${fixture}:${entry.name} contains a non-format URL`
          ).toBe(true);
        }
        for (const marker of xml.matchAll(/\b(?:NEUTRAL|ATLCLI)_[A-Z0-9_]+\b/g)) {
          observedMarkers.add(marker[0]);
          expect(PERMITTED_MARKERS).toContain(marker[0] as (typeof PERMITTED_MARKERS)[number]);
        }
        for (const content of extractContentValues(xml)) {
          expect(
            PERMITTED_METADATA.has(content) ||
              PERMITTED_MARKERS.includes(content as (typeof PERMITTED_MARKERS)[number])
          ).toBe(true);
        }
      }
    }

    for (const marker of PERMITTED_MARKERS) expect(observedMarkers).toContain(marker);

    for (const path of listTextFiles(FIXTURES_DIRECTORY)) {
      if (![".json", ".md", ".txt"].includes(extname(path))) continue;
      expectNoPrivateMaterial(path.slice(FIXTURES_DIRECTORY.length + 1), readFileSync(path, "utf8"));
    }
  });

  test("selected parser and resource caps have measured headroom and complete boundaries", () => {
    const analyses = BINARY_FIXTURES.map(analysisFor);
    const maxima = new Map<string, number>([
      [
        "maxXmlPartBytes",
        Math.max(...analyses.flatMap((analysis) => analysis.xml.parts.map((part) => part.bytes))),
      ],
      [
        "maxXmlPartCharacters",
        Math.max(
          ...analyses.flatMap((analysis) => analysis.xml.parts.map((part) => part.characters))
        ),
      ],
      [
        "maxXmlElementsPerPart",
        Math.max(...analyses.flatMap((analysis) => analysis.xml.parts.map((part) => part.elements))),
      ],
      ["maxXmlDepth", Math.max(...analyses.map((analysis) => analysis.xml.maxDepth))],
      [
        "maxXmlAttributesPerPart",
        Math.max(
          ...analyses.flatMap((analysis) => analysis.xml.parts.map((part) => part.attributes))
        ),
      ],
      [
        "maxXmlAttributeCharacters",
        Math.max(...analyses.map((analysis) => analysis.xml.maxAttributeCharacters)),
      ],
      [
        "maxRasterPixels",
        Math.max(...analyses.flatMap((analysis) => analysis.raster.map((asset) => asset.pixels))),
      ],
      [
        "maxRasterDimension",
        Math.max(
          ...analyses.flatMap((analysis) =>
            analysis.raster.flatMap((asset) => [asset.width, asset.height])
          )
        ),
      ],
      [
        "maxSvgBytes",
        Math.max(...analyses.flatMap((analysis) => analysis.svg.map((asset) => asset.bytes))),
      ],
      [
        "maxSvgElements",
        Math.max(...analyses.flatMap((analysis) => analysis.svg.map((asset) => asset.elements))),
      ],
      [
        "maxSvgDepth",
        Math.max(...analyses.flatMap((analysis) => analysis.svg.map((asset) => asset.maxDepth))),
      ],
      [
        "maxSvgAttributes",
        Math.max(...analyses.flatMap((analysis) => analysis.svg.map((asset) => asset.attributes))),
      ],
      [
        "maxSvgPathDataBytes",
        Math.max(
          ...analyses.flatMap((analysis) => analysis.svg.map((asset) => asset.pathDataBytes))
        ),
      ],
      [
        "maxSvgFilters",
        Math.max(...analyses.flatMap((analysis) => analysis.svg.map((asset) => asset.filters))),
      ],
    ]);
    const contract = JSON.parse(
      readFileSync(resolve(GOLDENS_DIRECTORY, "resource-caps.v1.json"), "utf8")
    ) as {
      aggregateZipBudgets: {
        maxEntries: number;
        maxSingleEntryUncompressedBytes: number;
        maxUncompressedBytes: number;
        status: string;
      };
      caps: Array<{
        boundaryPlan: {
          limit: number;
          limitMinusOne: number;
          limitPlusOne: number;
        };
        limit: number;
        measuredMaximum: number;
        name: string;
      }>;
      parser: {
        dependency: string;
        failClosedOn: string[];
        mode: string;
        version: string;
      };
    };

    expect(contract.parser).toEqual({
      dependency: "saxes",
      mode: "streaming-xmlns",
      version: "6.0.0",
      failClosedOn: ["doctype", "entity", "warning", "well-formedness"],
    });
    expect(contract.aggregateZipBudgets).toMatchObject({
      maxEntries: 2048,
      maxSingleEntryUncompressedBytes: 64 * 1024 * 1024,
      maxUncompressedBytes: 128 * 1024 * 1024,
      status: "unchanged",
    });

    for (const cap of contract.caps) {
      const measured = maxima.get(cap.name);
      expect(measured, `${cap.name} has no fixture measurement`).toBeDefined();
      expect(cap.measuredMaximum).toBe(measured!);
      if (measured! > 0) expect(cap.limit).toBeGreaterThanOrEqual(measured! * 4);
      expect(cap.boundaryPlan).toEqual({
        limit: cap.limit,
        limitMinusOne: cap.limit - 1,
        limitPlusOne: cap.limit + 1,
      });
    }
    expect(
      contract.caps.find((cap) => cap.name === "maxXmlPartBytes")?.limit
    ).toBeLessThan(contract.aggregateZipBudgets.maxSingleEntryUncompressedBytes);
  });
});

interface JourneyFixture {
  schema: string;
  stages: Array<{
    allowedNextActions: Array<{ command: string; kind: string }>;
    completion: string;
    stage: string;
  }>;
}

describe("T0 host-neutral UX contract", () => {
  const journeyPath = resolve(UX_DIRECTORY, "journey-state-table.v1.json");
  const contractsPath = resolve(UX_DIRECTORY, "contracts.v1.json");
  const journeyText = readFileSync(journeyPath, "utf8");
  const journey = JSON.parse(journeyText) as JourneyFixture;
  const transcriptPaths = readdirSync(UX_DIRECTORY)
    .filter((name) => /^\d{2}-.+\.txt$/.test(name))
    .sort()
    .map((name) => resolve(UX_DIRECTORY, name));

  test("schema/API fixtures use canonical JSON and freeze the seven journey stages", () => {
    expect(canonicalJson(JSON.parse(journeyText))).toBe(journeyText);
    const contractsText = readFileSync(contractsPath, "utf8");
    expect(canonicalJson(JSON.parse(contractsText))).toBe(contractsText);
    expect(journey.stages.map(({ stage }) => stage)).toEqual([
      "analyzing",
      "review-required",
      "ready-to-preview",
      "ready-to-build",
      "built",
      "source-changed",
      "blocked",
    ]);
  });

  test("all ten transcripts end with a stage-allowed exact action", () => {
    expect(transcriptPaths).toHaveLength(10);
    for (const path of transcriptPaths) {
      const text = readFileSync(path, "utf8").trimEnd();
      const lines = text.split("\n");
      const stage = lines.find((line) => line.startsWith("Stage: "))?.slice("Stage: ".length);
      const code = lines
        .find((line) => line.startsWith("Message-Code: "))
        ?.slice("Message-Code: ".length) as TemplateIntakeMessageCode | undefined;
      const next = lines.at(-1)?.slice("Next: ".length);

      expect(lines.some((line) => line.startsWith("What happened: "))).toBe(true);
      expect(lines.some((line) => line.startsWith("Current state: "))).toBe(true);
      expect(lines.some((line) => line.startsWith("Retained: "))).toBe(true);
      expect(lines.at(-1)).toStartWith("Next: ");
      expect(next).toBeDefined();
      expect(code && code in TEMPLATE_INTAKE_MESSAGES_V1).toBe(true);
      const stageContract = journey.stages.find((candidate) => candidate.stage === stage);
      expect(stageContract, `${basename(path)} uses an unknown stage`).toBeDefined();
      expect(stageContract!.allowedNextActions.map(({ command }) => command)).toContain(next!);
    }
  });

  test("failure transcripts explicitly retain the active draft", () => {
    for (const name of ["06-source-changed-recovery.txt", "07-build-blocker.txt"]) {
      const text = readFileSync(resolve(UX_DIRECTORY, name), "utf8");
      expect(text).toMatch(/^Retained: The active draft\b/m);
    }
  });

  test("the primary journey requires no internal implementation vocabulary", () => {
    const combined = transcriptPaths.map((path) => readFileSync(path, "utf8")).join("\n");
    expect(combined).not.toMatch(
      /\b(?:candidate ID|capability path|JSON editing|Editorial Indigo|OOXML|Typst)\b/i
    );
  });

  test("every transcript message is registered with bounded parameters and a visible fallback", () => {
    const usedCodes = new Set(
      transcriptPaths.map((path) => {
        const text = readFileSync(path, "utf8");
        return text.match(/^Message-Code: (.+)$/m)![1] as TemplateIntakeMessageCode;
      })
    );
    for (const code of usedCodes) expect(TEMPLATE_INTAKE_MESSAGES_V1[code]).toBeDefined();

    for (const [code, definition] of Object.entries(TEMPLATE_INTAKE_MESSAGES_V1)) {
      const schemas = definition.parameters as Readonly<
        Record<string, MessageParameterSchemaV1>
      >;
      for (const schema of Object.values(schemas)) {
        if (schema.type === "string") {
          expect(schema.maxLength).toBeGreaterThan(0);
          expect(schema.maxLength).toBeLessThanOrEqual(512);
        } else {
          expect(Number.isSafeInteger(schema.minimum)).toBe(true);
          expect(Number.isSafeInteger(schema.maximum)).toBe(true);
          expect(schema.maximum!).toBeGreaterThanOrEqual(schema.minimum!);
        }
      }
      expect(code).toStartWith("ATLCLI_PDF_TEMPLATE_");
    }

    const fallback = renderTemplateIntakeMessage(
      "ATLCLI_PDF_TEMPLATE_STATUS_RESUMED",
      { project: "./brand-pdf-template" },
      {}
    );
    expect(fallback.code).toBe("ATLCLI_PDF_TEMPLATE_STATUS_RESUMED");
    expect(fallback.text).toContain("[ATLCLI_PDF_TEMPLATE_STATUS_RESUMED]");
    expect(fallback.severity).toBe("info");
    expect(() =>
      renderTemplateIntakeMessage(
        "ATLCLI_PDF_TEMPLATE_STATUS_RESUMED",
        { project: "x".repeat(513) },
        {}
      )
    ).toThrow("bounded string schema");
  });

  test("usability success is explicit and bounded to four primary commands", () => {
    const script = readFileSync(resolve(UX_DIRECTORY, "usability-script.md"), "utf8");
    expect(script).toMatch(/at most four primary\s+commands/i);
    for (const concept of ["applied", "retained", "open", "unsupported"]) {
      expect(script.toLocaleLowerCase()).toContain(concept);
    }
    for (const task of [
      "Import the supplied Word document",
      "Explain which design choices will change",
      "Review the page graphic",
      "Produce and open the rendered design review",
    ]) {
      expect(script).toContain(task);
    }
  });
});
